    - name: Preparar e Compilar o Projeto
      run: |
        # 1. Se existir uma pasta 'src' na raiz, move para dentro de nRFBox
        if [ -d "src" ] && [ "$(ls -A src 2>/dev/null)" ]; then
          mkdir -p nRFBox/src
          cp -r src/* nRFBox/src/
        fi

        # 2. Se o arquivo platformio.ini estiver na raiz, copia para nRFBox
        if [ -f "platformio.ini" ]; then
          cp platformio.ini nRFBox/
        fi

        # 3. Entra na pasta e roda a compilação
        cd nRFBox
        pio run
        
